CREATE FUNCTION CLIENTES.FN_COBRA_HABERES_EN_BLP (
	PCLIENTE_ID BIGINT ) 
	RETURNS SMALLINT   
	LANGUAGE SQL 
	SPECIFIC CLIENTES.FN_COBRA_HABERES_EN_BLP 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
---------------------------------------------------------* 
--RETORNA SI EN CLIENTE COBRA HABERES EN BLP 0(NO) 1(SI) * 
---------------------------------------------------------*
DECLARE VTIPO_DOCUMENTO INTEGER DEFAULT 0 ; 
DECLARE VNUMERO_DOCUMENTO BIGINT DEFAULT 0 ; 
DECLARE VTIPO_CLIENTE VARCHAR ( 050 ) DEFAULT '' ; 
DECLARE VTIPO_DOCUMENTO_SBI INTEGER DEFAULT 0 ; 
DECLARE VCOBRA_HABERES_EN_BLP SMALLINT DEFAULT NULL;  
  
IF PCLIENTE_ID IS NULL THEN 
SET VCOBRA_HABERES_EN_BLP = NULL ; 
GOTO FIN ; 
END IF;
 
--  Recupero valores de parametros necesarios para calculo de ventas 
--  Tipo y Número de Documento 
CALL CLIENTES . SP_RECUPERAR_TIPO_NRODOC_CLIENTE ( PCLIENTE_ID , 
VTIPO_DOCUMENTO , VNUMERO_DOCUMENTO ) ; 
  
--  Tipo Cliente 
CALL CLIENTES . SP_RECUPERAR_TIPO_CLIENTE ( VTIPO_DOCUMENTO , 
VTIPO_CLIENTE ) ; 

IF VTIPO_CLIENTE <> 'PF' THEN 
SET VCOBRA_HABERES_EN_BLP = NULL ; 
GOTO FIN ; 
END IF;
  
--Recupero tipo de documento original 
--Para Clientes que cambiaron el tipo de documento 
SET VTIPO_DOCUMENTO_SBI = 
INT ( SUBSTR ( DIGITS ( DEC ( PCLIENTE_ID , 13 , 0 ) ) , 1 , 2 ) ) ; 

--
WITH PRECALIFICADOS_COBRAEN_BLP AS 
(SELECT CASE WHEN COUNT ( * ) > 0 THEN 1 ELSE 0 END AS COBRA_EN_BLP 
FROM BL2SADATA . CREMPHABB1 
WHERE CRULTRAMO = 'S' AND 
CRTIPDOCE = VTIPO_DOCUMENTO_SBI AND 
CRNRODOCE = VNUMERO_DOCUMENTO AND CRPROMACAJ > 0 
GROUP BY CRSUCCTA , CRSISCTA , CRTIPCTA , CRNROCTA , CRPROMACAJ ) , 
NOPRECALIFICADOS_COBRAEN_BLP AS 
( SELECT CASE WHEN COUNT ( * ) > 0 THEN 1 ELSE 0 END AS COBRA_EN_BLP 
  FROM CLIENTES . ACTIVIDAD_CLIENTE 
WHERE CLIENTE_ID = PCLIENTE_ID AND 
IFNULL ( TIPO_ACTIVIDAD_ID , 0 ) IN ( 1 , 2 ) 
AND IFNULL ( ACREDITACION_SUELDO_ID , 0 ) = 1 ) 
SELECT COBRA_EN_BLP INTO VCOBRA_HABERES_EN_BLP 
FROM 
( SELECT COBRA_EN_BLP FROM NOPRECALIFICADOS_COBRAEN_BLP 
UNION 
SELECT COBRA_EN_BLP FROM PRECALIFICADOS_COBRAEN_BLP ) AS T 
ORDER BY COBRA_EN_BLP DESC 
FETCH FIRST 1 ROW ONLY ;   

FIN:
RETURN VCOBRA_HABERES_EN_BLP;
END